//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WashCoat.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabData1
    {
        public int ID { get; set; }
        public string BatchID { get; set; }
        public string LabLogNumber { get; set; }
        public double Solids500C { get; set; }
        public double Pt { get; set; }
        public double Pd { get; set; }
        public double Rh { get; set; }
        public double Zr { get; set; }
        public double Ce { get; set; }
        public double Ni { get; set; }
        public double Ba { get; set; }
        public double La { get; set; }
        public double Ir { get; set; }
        public double pH { get; set; }
        public double Y { get; set; }
        public double Nd { get; set; }
        public double Pr { get; set; }
        public double Hf { get; set; }
        public double Temperature { get; set; }
        public double Viscosity_Fresh { get; set; }
        public double Viscosity_Aged { get; set; }
        public double Arizona_Solids { get; set; }
        public double WashCoatLoading { get; set; }
    }
}
