//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WashCoat.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tank
    {
        public int TankID { get; set; }
        public int LabDataID { get; set; }
        public int LoopLine { get; set; }
    }
}
